# 배열을 파일에 저장 및 불러오기
- ## 바이너리 파일로 저장/불러오기
    - ### np.save("파일경로", 배열)
        - 배열을 raw 바이너리 형식으로 저장한다. (압축하지 않은)
        - 파일명에 확장자로 npy를 붙인다. (무조건 붙인다. abc.xxx 해도 abc.xxx.npy 로 저장)
    - ### np.load("파일경로") 
        - 파일에 저장된 배열을 불러온다.
    - ### np.savez("파일경로", 이름=배열, 이름=배열, ...)
        - 여러개의 배열을 저장할 때 사용
        - 파일명에 확장자로 npz가 붙는다.
        - 내부적으로 압축해서 저장한다.
        - load() 함수로 불러오면 저장된 배열목록이 반환 된다. 저장시 지정한 이름을 이용해 조회 
- ## 텍스트 파일로 저장하고 불러오기
    - ### savetxt("파일경로", 배열 [, delimiter='공백') 
        - 텍스트 형태로 저장.
        - 각 원소는 공백을 기준으로 나뉘며 delimiter 속성으로 구분자를 지정할 수 있다. (delimiter생략시 공백)
        - 1차원과 2차원 배열만 저장 가능하다. (3차원 이상은 저장이 안된다.)
    - ### loadtxt("파일경로" [,dtype=float, delimiter=공백)

In [1]:
import numpy as np

a = np.array([1,5,8,9,10])  #1차원
b = np.ones(shape=(3,4,2))  #3차원
c = np.random.normal(size=(5,10)) # 2차원

print(a.shape, b.shape, c.shape)

(5,) (3, 4, 2) (5, 10)


In [4]:
# 저장 - binary 형식으로 저장
import os
# 저장할 디렉토리가 없으면 만들어라.
save_dir = 'save_data'
if not os.path.isdir(save_dir): # save_data 디렉토리가 있는지 여부 확인 - 디렉토리가 없으면
    os.mkdir(save_dir) #디렉토리 생성.
np.save("save_data/a", a)  #a 배열을 save_data/a.npy 파일에 저장

In [5]:
np.save('save_data/b', b)
np.save('save_data/c', c)

In [7]:
# binary 로 저장된 배열을 불러오기
a2 = np.load('save_data/a.npy')
print(a2.shape)
a2

(5,)


array([ 1,  5,  8,  9, 10])

In [8]:
b2 = np.load('save_data/b.npy')
print(b2.shape)
b2

(3, 4, 2)


array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
c2 = np.load('save_data/c.npy')
print(c2.shape)

(5, 10)


In [10]:
c

array([[-0.92592568, -1.03778481,  0.55576444, -0.49293227,  0.03434812,
        -0.25166787,  0.84643024,  0.10513984,  0.38947237, -0.2923898 ],
       [-0.31827446, -0.80046234, -0.46929609, -0.66502206,  1.85990938,
         0.49512339, -0.64439872, -2.5328424 , -1.08892281, -0.16423049],
       [-1.26650079, -0.41386438, -0.55346401, -0.65025846,  2.18474865,
        -1.94519893,  1.27729472, -0.55880841, -2.64953243,  0.14918915],
       [ 0.49148865,  0.74526273, -1.68700183,  0.72059506, -0.49810031,
         0.38994436,  1.69777007, -1.10918139,  0.55235269, -0.31471092],
       [-0.70948814,  0.86390438,  1.42795679, -0.17072126,  0.88241512,
        -1.17041331, -2.02257187, -0.38913814, -0.08612742,  1.42200813]])

In [11]:
c2

array([[-0.92592568, -1.03778481,  0.55576444, -0.49293227,  0.03434812,
        -0.25166787,  0.84643024,  0.10513984,  0.38947237, -0.2923898 ],
       [-0.31827446, -0.80046234, -0.46929609, -0.66502206,  1.85990938,
         0.49512339, -0.64439872, -2.5328424 , -1.08892281, -0.16423049],
       [-1.26650079, -0.41386438, -0.55346401, -0.65025846,  2.18474865,
        -1.94519893,  1.27729472, -0.55880841, -2.64953243,  0.14918915],
       [ 0.49148865,  0.74526273, -1.68700183,  0.72059506, -0.49810031,
         0.38994436,  1.69777007, -1.10918139,  0.55235269, -0.31471092],
       [-0.70948814,  0.86390438,  1.42795679, -0.17072126,  0.88241512,
        -1.17041331, -2.02257187, -0.38913814, -0.08612742,  1.42200813]])

In [12]:
# 세개의 배열을 한파일에 저장 (N개를 한파일에 저장)
np.savez('save_data/all', arr_a=a, arr_b=b, arr_c=c)

In [ ]:
# npz 파일 읽어오기 -> load()
arr_all = np.load('save_data/all.npz')

In [14]:
# 저장할때 지정한 이름 조회
arr_all.files

['arr_a', 'arr_b', 'arr_c']

In [15]:
a3 = arr_all['arr_a']
b3 = arr_all['arr_b']
c3 = arr_all['arr_c']

In [16]:
a3

array([ 1,  5,  8,  9, 10])

In [17]:
b3

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [19]:
c

array([[-0.92592568, -1.03778481,  0.55576444, -0.49293227,  0.03434812,
        -0.25166787,  0.84643024,  0.10513984,  0.38947237, -0.2923898 ],
       [-0.31827446, -0.80046234, -0.46929609, -0.66502206,  1.85990938,
         0.49512339, -0.64439872, -2.5328424 , -1.08892281, -0.16423049],
       [-1.26650079, -0.41386438, -0.55346401, -0.65025846,  2.18474865,
        -1.94519893,  1.27729472, -0.55880841, -2.64953243,  0.14918915],
       [ 0.49148865,  0.74526273, -1.68700183,  0.72059506, -0.49810031,
         0.38994436,  1.69777007, -1.10918139,  0.55235269, -0.31471092],
       [-0.70948814,  0.86390438,  1.42795679, -0.17072126,  0.88241512,
        -1.17041331, -2.02257187, -0.38913814, -0.08612742,  1.42200813]])

In [18]:
c3

array([[-0.92592568, -1.03778481,  0.55576444, -0.49293227,  0.03434812,
        -0.25166787,  0.84643024,  0.10513984,  0.38947237, -0.2923898 ],
       [-0.31827446, -0.80046234, -0.46929609, -0.66502206,  1.85990938,
         0.49512339, -0.64439872, -2.5328424 , -1.08892281, -0.16423049],
       [-1.26650079, -0.41386438, -0.55346401, -0.65025846,  2.18474865,
        -1.94519893,  1.27729472, -0.55880841, -2.64953243,  0.14918915],
       [ 0.49148865,  0.74526273, -1.68700183,  0.72059506, -0.49810031,
         0.38994436,  1.69777007, -1.10918139,  0.55235269, -0.31471092],
       [-0.70948814,  0.86390438,  1.42795679, -0.17072126,  0.88241512,
        -1.17041331, -2.02257187, -0.38913814, -0.08612742,  1.42200813]])

In [22]:
a

array([ 1,  5,  8,  9, 10])

In [27]:
# 텍스트파일로 저장 => 1차원, 2차원 배열만 가능
np.savetxt("save_data/b_txt.csv", a, delimiter=',')

In [28]:
a4 = np.loadtxt('save_data/b_txt.csv')
a4

array([ 1.,  5.,  8.,  9., 10.])

In [29]:
np.savetxt('save_data/c.csv', c)

In [30]:
np.savetxt('save_data/c_2.csv', c, delimiter=',')

In [32]:
c4 = np.loadtxt('save_data/c.csv')
c4.shape
c4

array([[-0.92592568, -1.03778481,  0.55576444, -0.49293227,  0.03434812,
        -0.25166787,  0.84643024,  0.10513984,  0.38947237, -0.2923898 ],
       [-0.31827446, -0.80046234, -0.46929609, -0.66502206,  1.85990938,
         0.49512339, -0.64439872, -2.5328424 , -1.08892281, -0.16423049],
       [-1.26650079, -0.41386438, -0.55346401, -0.65025846,  2.18474865,
        -1.94519893,  1.27729472, -0.55880841, -2.64953243,  0.14918915],
       [ 0.49148865,  0.74526273, -1.68700183,  0.72059506, -0.49810031,
         0.38994436,  1.69777007, -1.10918139,  0.55235269, -0.31471092],
       [-0.70948814,  0.86390438,  1.42795679, -0.17072126,  0.88241512,
        -1.17041331, -2.02257187, -0.38913814, -0.08612742,  1.42200813]])

In [35]:
c5 = np.loadtxt('save_data/c_2.csv', delimiter=',') #delimiter는 저장할 때 지정한 것과 동일한 것을 지정한다.
c5.shape

(5, 10)

In [36]:
np.savetxt('test', b) #b: 3차원배열 => text로 저장은 1,2차원만 가능

ValueError: Expected 1D or 2D array, got 3D array instead

In [38]:
a.dtype

dtype('int32')

In [42]:
a5 = np.loadtxt('save_data/a_txt.csv', dtype='int32')
a5.dtype

dtype('int32')

In [43]:
a5

array([ 1,  5,  8,  9, 10])

In [45]:
import pandas as pd
df = pd.read_csv('save_data/c_2.csv', header=None)
df

0         1         2         3         4         5         6  \
0 -0.925926 -1.037785  0.555764 -0.492932  0.034348 -0.251668  0.846430   
1 -0.318274 -0.800462 -0.469296 -0.665022  1.859909  0.495123 -0.644399   
2 -1.266501 -0.413864 -0.553464 -0.650258  2.184749 -1.945199  1.277295   
3  0.491489  0.745263 -1.687002  0.720595 -0.498100  0.389944  1.697770   
4 -0.709488  0.863904  1.427957 -0.170721  0.882415 -1.170413 -2.022572   

          7         8         9  
0  0.105140  0.389472 -0.292390  
1 -2.532842 -1.088923 -0.164230  
2 -0.558808 -2.649532  0.149189  
3 -1.109181  0.552353 -0.314711  
4 -0.389138 -0.086127  1.422008